#!/bin/bash
# -----------------------------------------------------------------------------
# docker-yavdr start script
# written by Jonadalar
#
# based on: Isaac Bythewood
# -----------------------------------------------------------------------------

# initial start of YAVDR init scripts here!
if [ ! -f /etc/yavdr/postinstall-started ]
then
  /usr/sbin/yavdr-post-install
  touch /etc/yavdr/postinstall-started
fi

# Run supervisor which maintains the further init process
/usr/bin/supervisord

